use_frameworks!

platform :ios, '15.0'

target 'FavorletApp2App_Example' do
  pod 'FavorletApp2App', :path => '../'
  
  # DIKit (https://github.com/Liftric/DIKit/tree/release)
  pod 'DIKit', '~> 1.6'
  

  target 'FavorletApp2App_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
